steps:

  ### Pull for optimization docker build time
  - name: 'gcr.io/cloud-builders/docker'
    id: 'Pull'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull asia-northeast3-docker.pkg.dev/$PROJECT_ID/newv/ui:latest || exit 0

  ### Build
  - id: 'Build'
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t',
      'asia-northeast3-docker.pkg.dev/$PROJECT_ID/newv/ui:$SHORT_SHA',
      '--cache-from',
      'asia-northeast3-docker.pkg.dev/$PROJECT_ID/newv/ui:latest',
      '.'
    ]

  ### Publish
  - id: 'Publish'
    name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker push asia-northeast3-docker.pkg.dev/$PROJECT_ID/newv/ui:$SHORT_SHA

  ### Set image tag
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Set image tag'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        sed -i "s/image:.*/image: asia-northeast3-docker.pkg.dev\/$PROJECT_ID\/newv\/ui:$SHORT_SHA/g" k8s/newv-ui-deployment.yaml

  ### Deploy
  - id: 'Deploy'
    name: 'gcr.io/cloud-builders/gcloud'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}
        PROJECT=$(gcloud config get-value core/project)
        ZONE=${_CLOUDSDK_COMPUTE_ZONE}
        gcloud container clusters get-credentials "$${CLUSTER}" \
          --project "$${PROJECT}" \
          --zone "$${ZONE}"
        
        kubectl apply -f k8s/newv-ui-deployment.yaml

  ### Trigger deployment update
  - name: 'gcr.io/cloud-builders/kubectl'
    id: 'Set deployment image'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=${_CLOUDSDK_COMPUTE_ZONE}'
      - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLOUDSDK_CONTAINER_CLUSTER}'
    args: [
      'set',
      'image',
      'deployment',
      'newv-ui',
      'newv-ui-app=asia-northeast3-docker.pkg.dev/$PROJECT_ID/newv/ui:$SHORT_SHA'
    ]

  ### Add the latest tag to new image
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Tag'
    args:
      [
        'container',
        'images',
        'add-tag',
        'asia-northeast3-docker.pkg.dev/$PROJECT_ID/newv/ui:$SHORT_SHA',
        'asia-northeast3-docker.pkg.dev/$PROJECT_ID/newv/ui:latest',
      ]