apiVersion: apps/v1
kind: Deployment
metadata:
  name: newv-ui
  labels:
    app: newv-ui
spec:
  selector:
    matchLabels:
      app: newv-ui
      tier: web
  template:
    metadata:
      labels:
        app: newv-ui
        tier: web
    spec:
      containers:
        - name: newv-ui-app
          image: asia-northeast3-docker.pkg.dev/newv-project-1/newv/ui:v1
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /api/ping
              port: 3000
              scheme: HTTP
            periodSeconds: 5
            successThreshold: 1
            timeoutSeconds: 40
            initialDelaySeconds: 10
          ports:
            - containerPort: 3000
      restartPolicy: Always